import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    saveFabLight: {
      position: 'absolute',
      right: 18,
      bottom: 22,
      width: 58,
      height: 58,
      borderRadius: 29,
      backgroundColor: '#111111',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.25,
      shadowRadius: 5,
      elevation: 6,
    },
    saveFabDark: {
      position: 'absolute',
      right: 18,
      bottom: 22,
      width: 58,
      height: 58,
      borderRadius: 29,
      backgroundColor: '#ffffff',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.25,
      shadowRadius: 5,
      elevation: 6,
    },
  container: {
    flex: 1,
  },
  containerLight: {
    backgroundColor: '#f5f5f5',
  },
  containerDark: {
    backgroundColor: '#0b0b0b',
  },
  content: {
    padding: 16,
    paddingTop: 8,
    paddingBottom: 110,
    gap: 12,
  },
    topBar: {
      marginTop: 8,
      marginBottom: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
    },
  textLight: {
    color: '#111111',
  },
  textDark: {
    color: '#f2f2f2',
  },
  cameraTile: {
    borderRadius: 14,
    borderWidth: 1,
    height: 210,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    gap: 8,
  },
  cameraTileLight: {
    backgroundColor: '#ffffff',
    borderColor: '#cfcfcf',
  },
  cameraTileDark: {
    backgroundColor: '#111111',
    borderColor: '#3a3a3a',
  },
  cameraTileText: {
    fontSize: 15,
    fontWeight: '700',
    textTransform: 'uppercase',
    color: '#111111',
  },
  cardLight: {
    borderColor: '#cfcfcf',
    backgroundColor: '#fff',
  },
  cardDark: {
    borderColor: '#3a3a3a',
    backgroundColor: '#151515',
  },
  preview: {
    width: '100%',
    height: 210,
  },
  photoActionsRow: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  photoActionIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoActionIconButtonLight: {
    backgroundColor: '#ffffff',
    borderColor: '#cfcfcf',
  },
  photoActionIconButtonDark: {
    backgroundColor: '#151515',
    borderColor: '#3a3a3a',
  },
  label: {
    marginTop: 6,
    fontSize: 15,
    fontWeight: '700',
  },
  input: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    minHeight: 56,
    textAlignVertical: 'top',
  },
  inputLight: {
    borderColor: '#cfcfcf',
    color: '#111111',
    backgroundColor: '#fff',
  },
  inputDark: {
    borderColor: '#474747',
    color: '#f2f2f2',
    backgroundColor: '#151515',
  },
  descriptionInput: {
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    minHeight: 120,
    textAlignVertical: 'top',
  },
  characterCount: {
    color: '#8d8d8d',
    fontSize: 12,
    textAlign: 'right',
    marginTop: -6,
  },
  errorText: {
    color: '#b42318',
    fontWeight: '700',
  },
  saveFab: {
    position: 'absolute',
    right: 18,
    bottom: 22,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#111111',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 6,
  },
  previewModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.95)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  previewModalCloseButton: {
    position: 'absolute',
    top: 52,
    right: 16,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  previewModalImage: {
    width: '100%',
    height: '84%',
  },
});
